name: custom-multi-job-workflow

# Triggas manuellt istället för på push/pull
on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    env:
      GREETING: "Hello"
      SECRET_MESSAGE: ${{ secrets.SECRET_MESSAGE }}
    steps:
      - name: Print Greeting and Secret
        run: |
          echo "$GREETING, this is the first job."
          echo "Secret message is: $SECRET_MESSAGE"

  job2:
    runs-on: ubuntu-latest
    needs: job1  # job2 körs efter att job1 är klart
    env:
      GREETING: "Hi again"
    steps:
      - name: Print Greeting from Job 2
        run: |
          echo "$GREETING from job2, running after job1"
